data:
  csv_path: "../../../data/processed_data/dataset.csv"

  feature_cols:
    - station_id
    - Barometer
    - HumOut
    - RainDay
    - WindSpeed
    - WindSpeed10Min
    - wind_sin
    - wind_cos

  target_cols:
    - TempOut

  input_window: 20
  output_window: 2

training:
  batch_size: 128
  learning_rate: 0.001
  epochs: 100
  device: "cuda"
  rounds: 20
  n_splits: 5           # folds for TimeSeriesSplit cross-validation

  checkpoint_dir: "../../../data/trained_model/checkpoints/crossformer"
  checkpoint_every: 5

  early_stopping_patience: 20
  early_stopping_min_delta: 0.00001

model:
  input_dim: 8          # len(feature_cols)
  output_dim: 1
  d_model: 64
  nhead: 4
  num_layers: 2
  dropout: 0.1
  block_size: 4         # input_window (20) % block_size == 0